application: twothirdsgame
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /.*
  script: twothirdsgame.app


libraries:
- name: jinja2
  version: latest
